# Generated by Django 3.0 on 2019-12-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostafandy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='available_now',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='available_today',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='craft',
            field=models.IntegerField(choices=[(1, 'Carpentry'), (2, 'Electrical'), (3, 'Plumbing')], default=1),
            preserve_default=False,
        ),
    ]
